WIP: Add option to export library as webgmex at export
webgme/webgme-engine pull request #333
Opened 2024-07-16 21:22 UTC by pmeijer

2024-07-19 06:44 UTC, kecso requested changes
I like it in general, and if there is no change required in regards my comments, I can live with that :).

2024-07-19 06:44 UTC, kecso commented on src/common/util/serialization.js
> +                    delete rawJson.kind; // This is lost at this point.
i believe i know where this come from, but is this really the good behavior?
shouldn't we enhance the library info with the kind to begin with?

2024-07-19 06:44 UTC, kecso commented on test/server/worker/simpleworker.spec.js
any chance to add a test that would use the exported libary and run some traversal to see if everything goes well during the read of the nodes?

2026-05-05 15:08 UTC, pmeijer commented
Create new if needed and target `main` instead of `master`.

2026-05-05 15:08 UTC, closed without merging